/* ARTERIAL AND/OR VENOUS EMBOLISM AND STROKE, CVA AND TIA (NON OBSTETRIC, NON CHRONIC ADULT)
SNOMED CODES; 164 */


SELECT c.concept_id, c.concept_name as condition_label, c.domain_id, c.vocabulary_id
FROM concept c
WHERE c.domain_id = 'Condition'
AND vocabulary_id = 'SNOMED'
AND (c.concept_name LIKE '%embol%'
OR c.concept_name LIKE '%stroke%'
OR c.concept_name LIKE '%cerebrovascular%')
AND c.concept_name NOT LIKE '%abort%'
AND c.concept_name NOT LIKE '%miscarriage%'
AND c.concept_name NOT LIKE '%heat stroke%'
AND c.concept_name NOT LIKE '%heatstroke%'
AND c.concept_name NOT LIKE '%sunstroke%'
AND c.concept_name NOT LIKE '%fat embol%'
AND c.concept_name NOT LIKE '%air embol%'
AND c.concept_name NOT LIKE '%pregnancy%'
AND c.concept_name NOT LIKE '%Embolism due to%'
AND c.concept_name NOT LIKE '%late effect of%'
AND c.concept_name NOT LIKE '%late effects of%'
AND c.concept_name NOT LIKE '%prenatal%'
AND c.concept_name NOT LIKE '%antenatal%'
AND c.concept_name NOT LIKE '%postnatal%'
AND c.concept_name NOT LIKE 'Congenital anomaly%'
AND c.concept_name NOT LIKE '%Amniotic%'
AND c.concept_name NOT LIKE '%Obstetric%'
AND c.concept_name NOT LIKE '%puerper%'
AND c.concept_name NOT LIKE '%syphilis%'
AND c.concept_name NOT LIKE '%apraxia%'
AND c.concept_name NOT LIKE '%cerebrovascular disease%'
AND c.concept_name NOT LIKE '%hereditary%'
AND c.concept_name NOT LIKE '%abscess%'
AND c.concept_name NOT LIKE '%paralytic%'
AND c.concept_name NOT LIKE '%chronic%'
AND c.concept_name NOT LIKE '%upstroke%'
AND c.concept_name NOT LIKE '%pain%'
AND c.concept_name NOT LIKE '%syndrome%'
AND c.concept_name NOT LIKE '%-induced%'
AND c.concept_name NOT LIKE '%completed%'
AND c.concept_name NOT LIKE '%tumor%'
AND c.concept_name NOT LIKE '%following stroke%'
AND c.concept_name NOT LIKE '%oil %'
AND c.concept_name NOT LIKE '%childbirth%'
AND c.concept_name NOT LIKE '%septic%'
AND c.concept_name NOT LIKE '% test%'
AND c.concept_name NOT LIKE ' sinus%'
AND c.concept_name NOT LIKE '%purpura%'
AND c.concept_name NOT LIKE '%neonatal%'
AND c.concept_name NOT LIKE '%nitrogen%'
AND c.concept_name NOT LIKE '%Methyl%'
AND c.concept_name NOT LIKE '%Barium%'
AND c.concept_name NOT LIKE '%At low risk of%'
AND c.concept_name NOT LIKE '%sequela of stroke%'
AND c.concept_name NOT LIKE '%graft%'
AND c.concept_name NOT LIKE '%Impending%'
AND c.concept_name NOT LIKE '%cholesterol embol%'
AND c.concept_name NOT LIKE '%microembol%'
AND c.invalid_reason IS NULL 
