/* Drugs for an Indication / drugsForAnIndication.sql

Replace Concept_ID in this Query with any generated by drugIndications.sql
This one is for "Cardiac Arrhythmias" 4266251

Kyle P. Rasku RN ~ March 25, 2020
*/

SELECT ingredient.concept_id AS ingredient_concept_id, 
       ingredient.concept_name AS ingredient_name, 
	   ancestor_detail.concept_name AS ancestor_name, 
	   ancestor_detail.vocabulary_id, 
	   ancestor_detail.concept_class_id
FROM concept ingredient, concept ancestor_detail, concept_ancestor ancestor
WHERE ancestor.descendant_concept_id = ingredient.concept_id
AND ancestor.ancestor_concept_id = ancestor_detail.concept_id 
AND ingredient.concept_class_id = 'Ingredient'
AND ingredient.vocabulary_id = 'RxNorm'
AND ancestor.ancestor_concept_id = 4266251
AND DATE('now') BETWEEN ingredient.valid_start_date AND ingredient.valid_end_date
